### ISSUE TITLE
Bezeichnung stört Smartmeter

### ISSUE THREAD

**Issue by Garfs-Homassistant** [REIZFLUT/ahoy-tasmota-solar-manager#1]
Mein hichi hat zusätzlich den Namen Haus 

leider kann daher der Wert nicht ausgelesen werden, wenn ich die Bezeichnung komplett lösche geht es, aus anderen Gründen soll das aber bleiben. Kann das rausgefiltert werden?

api sieht so aus:

{"StatusSNS":{"Time":"2023-07-28T20:13:40","Haus ":{"Total_in":27031.13,"Power_curr":1135}}}

**Comment by REIZFLUT** [comment]
Das Problem mit der Bezeichnung ist behoben. Diese wird nun automatisch erkannt.
Tausche die Datei app/sensors/SmartMeter.php gegen die neu hochgeladene aus, dann sollte er "Haus" automatisch erkennen.
In dem JSON String sehe ich jedoch ein weiteres Problem: Es fehlt "Total_out". Also der Zählerstand für die Einspeisung.
Vgl. {"StatusSNS":{"Time":"2023-07-29T10:18:31","":{"Total_in":12345.67,"Total_out":12.34,"Power_curr":12}}}

Kann das dein Zähler nicht? Zeigt er bei "Power_curr" Negativwerte bei der Einspeisung an?
Hier könnte man einen "virtuellen Einsspeise-Zähler" einführen, der zumindest ungefähr die Rückspeisung ins Netz addiert und für die Statistik zur Verfügung stellt. Das ist ein etwas größerer Aufwand, dass ich jetzt nicht so schnell lösen kann.

**Comment by Garfs-Homassistant** [comment]
Super, teste ich heute Abend 

ja der Zähler kann nur 1.8.0, 2.8.0 geht nicht, daher kein out

stromnetz schein den trotz Meldung auch nicht zu wechseln

und ja power_curr liefert negative werte, wenn ich mehr einspeise als ich verbrauche

**Comment by REIZFLUT** [comment]
Ich habe ein Feature hinzugefügt. Wenn das Projekt noch nicht installiert ist, bitte komplett neu ziehen. Ansonsten alle Daten außer den Ordner "database" neu ziehen und anschließend unter helper die datei settings_patch.php einmal ausführen.

**Comment by REIZFLUT** [comment]
Das Feature ist ein virtueller Einspeisezähler. Hier den Wert in den Settings auf 1 setzen, dann sollte es auch ohne Total_out funktionieren... ohne Gewähr ;-)

**Comment by Garfs-Homassistant** [comment]
Zählerstand und Verbrauch auch negativ wird erfasst. 

Negativ Zähler schaue ich morgen mal.

**Comment by Garfs-Homassistant** [comment]
Der virtuelle Zähler geht leider nicht. Habe jetzt 20 Minuten 400 Watt eingespeist und ca. 100-180 Watt als negativ gehabt, aber Zähler bleibt bei 0,00. entweder ist das zu wenig zum zählen oder etwas anderes stimmt nicht. 

Wenn ich unter Einstellungen die 1 setze, steht nach dem speichern auch kein Wert (weder 0 noch 1) mehr in dem Feld.

**Comment by REIZFLUT** [comment]
Ich tippe darauf, dass das Setting in der DB nicht existiert. Patch ausgeführt?

(http://url/helper/settings_patch.php)

Den Ordner inklusive Datei musst dir ggf. neu aus dem Repository ziehen.

**Comment by REIZFLUT** [comment]
Ich habe gerade noch einen Bug entdeckt. Bitte app/config.php gegen die neu hochgeladene austauschen. Dann sollte der Fehler behoben sein.

**Comment by Garfs-Homassistant** [comment]
Jetzt zählt er, super
