### ISSUE TITLE
Mehrere Wechselrichter

### ISSUE THREAD

**Issue by Garfs-Homassistant** [REIZFLUT/ahoy-tasmota-solar-manager#3]
Ich hab gerade gesehen (wollte das für meinen Nachbarn einrichten), wenn 2 Wechselrichter dran sind, werden nur die Daten vom ersten genommen. Kann man die 2 P_AC saldieren?

hier mal der Auszug aus der API

{"inverter":[[{"fld":"U_DC","unit":"V","val":"32.40"},{"fld":"I_DC","unit":"A","val":"0.43"},{"fld":"P_DC","unit":"W","val":"13.90"},{"fld":"YieldDay","unit":"Wh","val":"5.00"},{"fld":"YieldTotal","unit":"kWh","val":"201.97"},{"fld":"Irradiation","unit":"%","val":"3.66"},{"fld":"U_DC","unit":"V","val":"32.80"},{"fld":"I_DC","unit":"A","val":"0.42"},{"fld":"P_DC","unit":"W","val":"13.70"},{"fld":"YieldDay","unit":"Wh","val":"5.00"},{"fld":"YieldTotal","unit":"kWh","val":"201.24"},{"fld":"Irradiation","unit":"%","val":"3.61"},{"fld":"U_AC","unit":"V","val":"235.50"},{"fld":"I_AC","unit":"A","val":"0.11"},{"fld":"P_AC","unit":"W","val":"26.40"},{"fld":"Q_AC","unit":"var","val":"0.00"},{"fld":"F_AC","unit":"Hz","val":"49.99"},{"fld":"PF_AC","unit":"","val":"1.00"},{"fld":"Temp","unit":"Â°C","val":"17.70"},{"fld":"ALARM_MES_ID","unit":"","val":"1.00"},{"fld":"YieldDay","unit":"Wh","val":"10.00"},{"fld":"YieldTotal","unit":"kWh","val":"403.21"},{"fld":"P_DC","unit":"W","val":"27.60"},{"fld":"Efficiency","unit":"%","val":"95.65"}],[{"fld":"U_DC","unit":"V","val":"32.00"},{"fld":"I_DC","unit":"A","val":"0.45"},{"fld":"P_DC","unit":"W","val":"14.30"},{"fld":"YieldDay","unit":"Wh","val":"4.00"},{"fld":"YieldTotal","unit":"kWh","val":"31.98"},{"fld":"Irradiation","unit":"%","val":"3.76"},{"fld":"U_DC","unit":"V","val":"0.70"},{"fld":"I_DC","unit":"A","val":"0.01"},{"fld":"P_DC","unit":"W","val":"0.00"},{"fld":"YieldDay","unit":"Wh","val":"0.00"},{"fld":"YieldTotal","unit":"kWh","val":"0.00"},{"fld":"Irradiation","unit":"%","val":"0.00"},{"fld":"U_AC","unit":"V","val":"235.70"},{"fld":"I_AC","unit":"A","val":"0.06"},{"fld":"P_AC","unit":"W","val":"13.70"},{"fld":"Q_AC","unit":"var","val":"0.00"},{"fld":"F_AC","unit":"Hz","val":"50.00"},{"fld":"PF_AC","unit":"","val":"1.00"},{"fld":"Temp","unit":"Â°C","val":"28.00"},{"fld":"ALARM_MES_ID","unit":"","val":"3.00"},{"fld":"YieldDay","unit":"Wh","val":"4.00"},{"fld":"YieldTotal","unit":"kWh","val":"31.98"},{"fld":"P_DC","unit":"W","val":"14.30"},{"fld":"Efficiency","unit":"%","val":"95.80"}]]}

**Comment by REIZFLUT** [comment]
Das System misst ja nicht nur, sondern passt anhand der Messung die Leistung an.
Bei mehreren Wechselrichtern wird es schnell kompliziert. Werden alle gleichmäßig angepasst, oder gibt es eine Gewichtung, verändert sich ggf. die Gewichtung über den Tag etc. Deshalb momentan nur EIN Wechselrichter. Kann sein, dass ich irgendwann noch ein reines Messsystem schreibe, aber da gibt es ja schon 1000 Lösungen (HA, IO etc)

**Comment by Garfs-Homassistant** [comment]
Ich muss zugeben, ich wollte für ihn das nur als Messsystem missbrauchen. Weil es schnell und einfacher ist, als wegen sowas ein großes System aufzusetzen.
